### ISSUE TITLE
O365: Request is malformed or invalid

### ISSUE THREAD

**Issue by robert-winkler** [2e0byo/email#1]
Dear 2e0byo, 

your program looks like the solution to my problem!! 

Our institute/M$ switched off basic authentication and broke my workflow (offlineimap, notmuch/ alot.)

I modified your script for only one O365 account and run it from the CLI with  
`python oauth.py robert.winkler@cinvestav.mx`  

However, it fails.

my `oauth.py` looks as follows:

~~~
# path trickery for offlineimap. Other option is to install system-wide...
import sys
from argparse import ArgumentParser
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))

from email_auth import GmailCredentials, Office365Credentials

#Gmail_2e0byo = GmailCredentials(Path("~/.pass/2e0byo").expanduser(), "2e0byo@gmail.com")
#Wombat = GmailCredentials(
#    Path("~/.pass/Wombat").expanduser(), "jmwombat122@googlemail.com"
#)
Cinvestav = Office365Credentials(
    Path("~/.pass/Cinvestav").expanduser(),
#    "john.morris@durham.ac.uk",
    "robert.winkler@cinvestav.mx",
)


#ACCOUNTS = {x.user: x for x in {Gmail_2e0byo, Wombat, Durham}}
#ACCOUNTS |= {x.email: x for x in {Gmail_2e0byo, Wombat, Durham}}

ACCOUNTS = {x.user: x for x in {Cinvestav}}
ACCOUNTS |= {x.email: x for x in {Cinvestav}}

if __name__ == "__main__":
    parser = ArgumentParser()
    parser.add_argument("account", nargs="*")
    parser.add_argument("--refresh", help="Refresh token", action="store_true")
    parser.add_argument("--authstr", help="Xoauth2 string", action="store_true")
    args = parser.parse_args()
    for k in args.account:
        account = ACCOUNTS[k]
        if args.refresh:
            account.write_refresh_token()
        elif args.authstr:
            print(account.xoauth_string())
        else:
            print(account.authentication_token())
~~~
My password is stored in ~/.pass/Cinvestav  

console output:
~~~
Traceback (most recent call last):
  File "/home/rob/dataspace/nextcloud/src/email/email/oauth.py", line 40, in <module>
    print(account.authentication_token())
  File "/home/rob/dataspace/nextcloud/src/email/email/email_auth.py", line 58, in authentication_token
    raise Exception("Unable authenticate: " + resp.text)
Exception: Unable authenticate: {"error":"invalid_grant","error_description":"AADSTS9002313: Invalid request. Request is malformed or invalid.\r\nTrace ID: e47c143b-0a44-449a-8d8e-cc17f17e1101\r\nCorrelation ID: 33899385-9944-40bf-a4ca-75e3289e0a05\r\nTimestamp: 2023-01-19 19:53:41Z","error_codes":[9002313],"timestamp":"2023-01-19 19:53:41Z","trace_id":"e47c143b-0a44-449a-8d8e-cc17f17e1101","correlation_id":"33899385-9944-40bf-a4ca-75e3289e0a05","error_uri":"https://login.microsoftonline.com/error?code=9002313"}
~~~

BTW: I installed the `requirements.txt`; but the module `O365` was missing; I installed it separately. 

I just read your readme again (RTFM 😉). I'll need the 'machine email'!!! Where the hell can I find it?

Any idea?

**Comment by 2e0byo** [comment]
It depends on your provider.  For instance, at this university (and others) we are given a username like 'ab123' and also an email name like 'john.morris'. If you're not aware of having such an email, it might not be the problem.

But how do you know your password is stored in `~/.pass/Cinvestav`?  The way this library works you don't put anything in that file manually.  When you run `python oauth.py <account> --refresh` it will fire up a web browser and send you to your usual company login.  After logging in it will extract the refresh token from the resulting page and store it to that file (unless you implement another backend).  Then when you want to access your email you call it again with `--authstr` and it prints the xoauth2 authstr for use in the imap/smtp request; or if you can import python (e.g. from offlineimap) you import directly and hand the authentication token to the right function.

Nice catch with requirements.txt: this repo is a bit of a mess, so I'll clean it up and improve the readme. [done]

**Comment by 2e0byo** [comment]
closing as inactive; feel free to reopen.
