### ISSUE TITLE
Getting Office365 tokens: new ID/SECRET/URI needed?

### ISSUE THREAD

**Issue by raphaelfournier** [2e0byo/email#2]
Hello,
First, let me thank you a lot for this script. Minor point: it took me a while to figure what was supposed to be in the ~/.pass/Microsoft file (ie, nothing, but the README could state that, which was confirmed in your reply here: https://github.com/2e0byo/email/issues/1#issuecomment-1397651879).

It seems that Thunderbird secrets changed recently: https://blog.thunderbird.net/2023/01/important-message-for-microsoft-office-365-enterprise-users/.
I changed the ID from "08162f7c-0fd2-4200-a84a-f25a4db0b584" to "9e5f94bc-e8a4-4e73-b8be-63364c29d753" (according to line143 in https://searchfox.org/comm-central/source/mailnews/base/src/OAuth2Providers.jsm#143). 
However, when using the `python oauth.py <myemail> --refresh` command, I reach an error login page, saying that the "http://localhost:7598/" URI is the wrong one (precise message: "The redirect URI 'http://localhost:7598/' specified in the request does not match the redirect URIs configured for the application '9e5f94bc-e8a4-4e73-b8be-63364c29d753'"). 

Do you happen to know if some (other) parameters changed and what I can use to login successfully and get the precious token?

**Comment by 2e0byo** [comment]
Thanks!  Could you PR an improvement to the readme?  You can just click 'edit' I think in the github web interface and it will handle the rest.

It seems thunderbird now use https in the redirect; it should be fixed in https://github.com/2e0byo/email/commit/f408b716d51023dbdf10e87799fa3c181bf100af.
