### ISSUE TITLE
readme.md instructions don't match current code

### ISSUE THREAD

**Issue by baruchsiach** [2e0byo/email#3]
Configuration should probably be stored in `~/.config/email.toml`. Format is unclear.

`oauth.py` seems to move to `email_auth/cli.py`.

`requirements.txt` is not up to date. `pyproject.toml` is likely replacement.

**Comment by 2e0byo** [comment]
Sorry! only just seen this; I missed the notification.

This project got rewritten to work with nix; I'll try to have a look at it this weekend. Thanks for taking the time to open these issues.

**Comment by 2e0byo** [comment]
In case you're still interested @baruchsiach feel free to let me know if anything is now unclear. For now I'll close. Sorry for the delay.

**Comment by baruchsiach** [comment]
I managed to restore my email setup with offlineimap/msmtp against office-365. This is a great relief after two months of using their web interface following Debian testing Python 3.12 migration.

The distinction between poetry and plain venv is not entirely clear to me. Both seem to work here.

Thanks for your effort maintaining this package.

**Comment by 2e0byo** [comment]
Oh good!

The difference is just that in one case, poetry makes a venv and then you use it; in the other you build a standard package and then install it in a venv, using standard python tools. The end result is the same, but personally I like to keep development (with something like poetry) and packaging separate.

But if it would help you I can just publish this to pypi,  and then you can just `pipx install` or `pip install` it. Would that be useful?

**Comment by baruchsiach** [comment]
Anything that would make installation and integration easier is welcome.

Thank you very much.
