### ISSUE TITLE
Python 3.12 removed deprecated ssl.wrap_socket()

### ISSUE THREAD

**Issue by baruchsiach** [2e0byo/email#4]
This causes run-time failure:
```
  File ".../email_auth/creds.py", line 114, in get_response_url
    server.socket = ssl.wrap_socket(
                    ^^^^^^^^^^^^^^^
AttributeError: module 'ssl' has no attribute 'wrap_socket'
```
Instead, create a `ssl.SSLContext` object and call its `ssl.SSLContext.wrap_socket` method. See for example:
https://github.com/vmware/pyvmomi/issues/1057 .

**Comment by 2e0byo** [comment]
Thanks for the pointer!
